config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  #overwrites default /users/sign_in to /login and /users/sign_out to /logout 

  resources :products do
    resources :comments
  end
  resources :users

	#  get 'static_pages/index' - root is the home page
  root 'static_pages#index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  get 'payments/thank_you'

  post 'payments/create'

  # added in 4.3 for app/views/orders
  resources :orders, only: [:index, :show, :create, :destroy] 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ActionCable for pub/sub
  mount ActionCable.server => '/cable'
  resource  :session
  resources :examples

end
 

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments

  #5.9
  validates :name, presence: true

  #custom method for product to return the comment with the highest rating
  def highest_rating_comment
  	comments.rating_desc.first
	end

  #custom method for product to return the comment with the lowest rating
  def lowest_rating_comment
  	comments.rating_asc.first
	end

  #used for Raty
  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      # return our filtered list here
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
      @products = Product.all
    end

  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
  	
  	<div class="row">
		  <hr>
		  <p>
				<!-- issues occured because first_name was never received on the registration form -->
			  <%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
			  <% if signed_in? && current_user.admin? %>
			    <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
			  <% end %>
			</p>
		  <div class="rated" data-score="<%= comment.rating %>"></div>
			  <p><%= comment.body %></p>
			</div>
		<% end %>
</div>
 

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>

  <!-- generated by scaffolding for error messages: -->
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image_url %>
    <%= f.text_field :image_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :colour %>
    <%= f.text_field :colour, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <div class="new_comment">
    <h4>Add a review:</h4>
    <%= form_for([@product, @product.comments.build], remote: true) do |f| %>

      <%= f.label :body, "Comments" %>
      <%= f.text_area :body, class: "form-control" %>

      <div class="rating"></div>

      <div>
        <%= submit_tag("Send", class: "btn btn-info submit_comment") %> 
      </div> 

    <% end %>

  </div><!-- /.new_comment -->
<% end %>

app/views/products/_product.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
	<div class="product_box">
	<% cache product do %>
		<!-- creates an image that directs to the product's page when clicked. image and link are dynamic and correspond to each product -->
		<%= link_to image_tag(product.image_url, class: "img-responsive"), product %>
		<div class="product_box_description">
		  <h3><%= product.name %></h3>
		  <h4><%= product.description %></h4>
		  <p>Color: <%= product.colour %></p>
		  <p>Price: $<%= product.price %></p>

		 </div> 
	<% end %>	 
	</div>	
</div><!-- /col -->  

<% logger.debug "Product: #{product.name}"%>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="header">
  <h1>Products</h1>
</div>

<div class="container-fluid">
  <div class="row">
    <% cache(cache_key_for_products) do %>
      <%= render @products %>
    <% end %> 
  </div>
</div>

<br>


<!-- remove comment to view table

<table class="product-list">
  <thead>
    <tr>
      <th>Name</th>
      <th>ID</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Colour</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.colour %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

-->

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/newShow.html.erb
<!-- new code in testing for show.html.erb page -->

<p id="notice"><%= notice %></p>

<div id="productName">
	<h2><%= @product.name %></h2>		
</div>

<div class="container-fluid anchor" id="product-columns">
	<div class="row">

		<div class="col-xs-12 col-sm-3 col-md-3 product_image_box">
		  <%= link_to image_tag(@product.image_url, class: "img-responsive"), product %>			
		</div><!-- /.product_image_box -->

		<div class="col-xs-12 col-sm-6 col-md-6 product_info_box">
			<p><strong>Description:</strong><%= @product.description %></p>
			<p><strong>Colour:</strong><%= @product.colour %></p>
			<p><strong>Price:</strong><%= @product.price %></p>
		</div><!-- /.product_info_box -->

		<div class="col-xs-12 col-sm-3 col-md-3 product_action_box">
			<!-- reserved for quantity select -->
			<h3>Quantity:</h3>
			<select class="form-control">
			  <option>1</option>
			  <option>2</option>
			  <option>3</option>
			  <option>4</option>
			  <option>5</option>
			</select>

			<!-- reserved for add to cart button -->
			<button class="btn btn-default" type="submit">Add to Cart</button>
		</div><!-- /.product_action_box -->

		<div class="col-xs-12 product_comment_box">
			<h3>Reserved for comment title</h3>
			<p>Reserved for comment star rating *****</p>
			<p>Reserved for comment text</p>
		</div><!-- /.product_comment_box -->
	</div><!-- /.row -->
</div><!-- /#product-columns -->		

app/views/products/show.html.erb
<!-- new code in testing for show.html.erb page -->
<div class="container-fluid anchor" id="product-columns">
  <div class="row" data-product-id="<%= @product.id %>">

    <div class="col-xs-12 col-sm-4 col-md-6 product_image_box">
      <%= link_to image_tag(@product.image_url, data_zoom_image: @product.image_url, class: "img-responsive img-zoom"), @product %>     
    </div><!-- /.product_image_box -->

    <div class="col-xs-12 col-sm-8 col-md-6 product_info_box">
    <% cache @product do %>
      <div id="productName">
        <h2><%= @product.name %></h2>   
      </div>

      <div class="row"><!-- row level 2 -->
        <div class="col-xs-12 col-sm-6 col-md-6">


          <div id="productPrice">
            <h4>Price: <%= @product.price %></h4>
          </div>


          <p><strong>Average Rating: </strong><div class="rated" id="average-rating" data-score="<%= @product.average_rating %>"></div> </p>

          <p><strong>Colour: </strong><%= @product.colour %></p>


          <p><strong>Description: </strong><%= @product.description %></p>
          <% end %>
          <%= form_tag "/payments/create" do %>
            <%= render partial: "shared/stripe_checkout_button" %>
            <%= hidden_field_tag(:product_id, @product.id) %>
    <% end %>
        </div>  
<!-- 
        <div class="col-xs-12 col-sm-6 col-md-6">
          <h3>Quantity:</h3>
          <select class="form-control product_quantity">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
          </select>

          <button class="btn btn-default" type="submit">Add to Cart</button>
        </div> 
-->


      <!-- added in 5.8 -->
      <div class="col-xs-12 col-sm-12 col-md-12 container-fluid">

        <!-- _new_comment partial -->

          <%= render(:partial => "new_comment") %>

       </div><!-- /.container-fluid --> 
    </div><!-- /.product_info_box --></div><!-- /.row level 1 -->
      
  </div><!-- /.row level 1 -->    




</div><!-- /#product-columns -->    



<div class="col-xs-12 reviews_area">
  <h3>User reviews</h3>

<!-- alert to sub user that a new comment has been added -->
  <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>

  <!-- _comments partial -->
  <div class="comments_partial">
    <%= render(:partial => "comments") %>
  </div><!-- /.comments_partial -->

  <div class="product-reviews-pagination">
    <%= will_paginate @comments %>
  </div>

</div>  