config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  #overwrites default /users/sign_in to /login and /users/sign_out to /logout 

  resources :products do
    resources :comments
  end
  resources :users

	#  get 'static_pages/index' - root is the home page
  root 'static_pages#index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  get 'payments/thank_you'

  post 'payments/create'

  # added in 4.3 for app/views/orders
  resources :orders, only: [:index, :show, :create, :destroy] 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ActionCable for pub/sub
  mount ActionCable.server => '/cable'
  resource  :session
  resources :examples

end
 

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-fixed-top" role="navigation">
	  	<div class="container-fluid">
	  		<!-- this is the "hamburger" navbar -->
	  		<div class="navbar-header">
	  			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				    <span class="sr-only">Toggle navigation</span>
				    <span class="icon-bar"></span>
				    <span class="icon-bar"></span>
				    <span class="icon-bar"></span>
				  </button> 	

					<div class="projectName navbar-brand">
						<%= link_to "Rent-A-Cat", root_path %>
					</div><!-- end projectName -->						
	  		</div><!-- end navbar-header -->

	  		<!-- this is the standard navbar -->
	  		<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-left" id="rightul">
						<li><%= link_to "Shop", products_path %></li>
						<li><%= link_to "About", static_pages_about_path %></li>
						<li><%= link_to "Contact", static_pages_contact_path %></li>

					</ul><!-- / .navbar-collapse collapse -->

					<ul class="nav navbar-nav navbar-right" id="rightul">
					  <li>
					  <% if user_signed_in? %>
					    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
					  <% else %>
					    <%= link_to('Login', new_user_session_path) %>
					  <% end %>
					  </li>
					</ul><!-- / .nav pull-right -->			

				<!-- search bar-->
			  <%= form_tag("/products", method: "get", class: "navbar-form navbar-right") do %>
			  	<div class="form-group">
					  <%= text_field_tag(:q, nil, class: "form-control", id: "nav-form-control", placeholder: "") %>
					</div>
					  <%= submit_tag("Search", class: "btn btn-default", id: "nav-search-btn") %>
				<% end %>

				</div><!-- end navbar-collapse collapse -->	

	  	</div><!-- end nav container-fluid -->
	  	</div><!-- end .container-fluid -->
		</nav> <!-- end navbar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nameofapp</title>

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>



		<meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
  </head>

	<body>
		<!-- _nav partial -->
		<%= render 'layouts/nav' %>
		

		<!-- Devise gem: flash messages to display a welcome message when you sign in -->
		<% if notice %>
			<div id="notice" class="alert alert-info" role="alert"><%= notice %></div>
		<% end %>	

		<% if alert %>
		<div class="alert alert-danger" role="alert"><%= alert %></div>
		<% end %>


		<!-- where the view files are rendered inside the layout -->
		<div class ="rendered-content">
    	<%= yield %>
		</div>

		<footer>
		  &copy; 2016 Rent-A-Cat
		</footer>

  </body>
</html>